/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as FiguresRouteImport } from './routes/figures'
import { Route as PlayRouteImport } from './routes/play'
import { Route as FiguresIndexRouteImport } from './routes/figures.index'
import { Route as FiguresIdRouteImport } from './routes/figures.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresRoute = FiguresRouteImport.update({
  id: '/figures',
  path: '/figures',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIndexRoute = FiguresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FiguresRoute,
} as any)
const FiguresIdRoute = FiguresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FiguresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/figures': typeof FiguresRouteWithChildren
  '/play': typeof PlayRoute
  '/figures/$id': typeof FiguresIdRoute
  '/figures/': typeof FiguresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/play': typeof PlayRoute
  '/figures/$id': typeof FiguresIdRoute
  '/figures': typeof FiguresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/figures': typeof FiguresRouteWithChildren
  '/play': typeof PlayRoute
  '/figures/$id': typeof FiguresIdRoute
  '/figures/': typeof FiguresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/claims' | '/figures' | '/play' | '/figures/$id' | '/figures/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/claims' | '/play' | '/figures/$id' | '/figures'
  id:
    | '__root__'
    | '/'
    | '/claims'
    | '/figures'
    | '/play'
    | '/figures/$id'
    | '/figures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimsRoute: typeof ClaimsRoute
  FiguresRoute: typeof FiguresRouteWithChildren
  PlayRoute: typeof PlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures': {
      id: '/figures'
      path: '/figures'
      fullPath: '/figures'
      preLoaderRoute: typeof FiguresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/': {
      id: '/figures/'
      path: '/'
      fullPath: '/figures/'
      preLoaderRoute: typeof FiguresIndexRouteImport
      parentRoute: typeof FiguresRoute
    }
    '/figures/$id': {
      id: '/figures/$id'
      path: '/$id'
      fullPath: '/figures/$id'
      preLoaderRoute: typeof FiguresIdRouteImport
      parentRoute: typeof FiguresRoute
    }
  }
}

interface FiguresRouteChildren {
  FiguresIdRoute: typeof FiguresIdRoute
  FiguresIndexRoute: typeof FiguresIndexRoute
}

const FiguresRouteChildren: FiguresRouteChildren = {
  FiguresIdRoute: FiguresIdRoute,
  FiguresIndexRoute: FiguresIndexRoute,
}

const FiguresRouteWithChildren =
  FiguresRoute._addFileChildren(FiguresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimsRoute: ClaimsRoute,
  FiguresRoute: FiguresRouteWithChildren,
  PlayRoute: PlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
